name: Windmill Pull Request
on:
  push:

jobs:
  submit_pull_requests:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Submitting pull request"
